### ISSUE TITLE
Missing required module 'OpenCCBridge' after upgrade to 1.0.1

### ISSUE THREAD

**Issue by hustlzp** [ddddxxx/SwiftyOpenCC#10]
When I upgrade SwifyOpenCC from 1.0.0 to 1.0.1 and then compile my project.

Then it failed with the following error:

![屏幕快照 2019-10-27 上午11 06 59](https://user-images.githubusercontent.com/1180240/67629108-84f19900-f8ac-11e9-8059-cbd500cb5d79.png)

Downgrade to 1.0.0 solve the problem.

**Comment by ddddxxx** [comment]
There's `OpenCCBridge.framework` file in your Carthage/Build directory, add it to your project.

Swift PM is recommended since v1.0.1.
