### ISSUE TITLE
Redefinition of module 'OpenCCBridge'

### ISSUE THREAD

**Issue by bjdehang** [ddddxxx/SwiftyOpenCC#11]
使用“Swift Packages”方式，编译报错Redefinition of module 'OpenCCBridge'

**Comment by ddddxxx** [comment]
未能复现。可否提供出错的 package?

**Comment by bjdehang** [comment]
好的 不好意思，我这边再检查一下吧。
在 2020年2月14日 +0800 PM3:53，ddddxxx <notifications@github.com>，写道：
