### ISSUE TITLE
在真机上有错误发生

### ISSUE THREAD

**Issue by Joey-Lee** [ddddxxx/SwiftyOpenCC#2]
malloc: *** mach_vm_map(size=3852439552) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug

模拟器上挺好使，但在真机上运行，当ChineseConverter初始化时就出现上述错误：
let converter = ChineseConverter(option: [.traditionalize, .TWStandard, .TWIdiom])

**Comment by ddddxxx** [comment]
未能复现。

崩溃时调用栈是什么样的，内存状况如何？

请确保使用最新的版本（v0.2.2），之前的版本有内存泄漏的问题。

**Comment by ddddxxx** [comment]
close due to inactivity
