### ISSUE TITLE
在iphone5上面會crash

### ISSUE THREAD

**Issue by jwliang1226** [ddddxxx/SwiftyOpenCC#4]
mach_vm_map(size=3852439552) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug

只有在只有比較低memory的實體機上面會crash，模擬器看不出來的
實際測試iphone5無法執行ChineseConverter，因為一次配置過大記憶體導致當機。

**Comment by ddddxxx** [comment]
因为转换用的字典较大，可能出现这样的问题。你可以试试0.2.0版本，其中包含ChineseConverter.Options.textDict，可以使用文本格式的字典（极其慢）。

注意该版本有内存泄漏的问题，如果能用，你可以fork一份加上后来的patch

**Comment by jwliang1226** [comment]
請問後來的patch是指哪些呢？
我看似乎無法只單獨加memory leak的那一份patch

**Comment by ddddxxx** [comment]
把 cf245e1 cherry pick 过去应该可行。你先确认一下0.2.0能不能用。

**Comment by jwliang1226** [comment]
0.2.0 版本一樣會記憶體不足

**Comment by ddddxxx** [comment]
这样我就无能为力了，本项目只是对 https://github.com/BYVoid/OpenCC 的 wrapper。

**Comment by ddddxxx** [comment]
正式版已发布，不支持文本格式的字典。预计将来也不会降低对 memory 的要求。
