### ISSUE TITLE
Support Xcode 10.2

### ISSUE THREAD

**Issue by hustlzp** [ddddxxx/SwiftyOpenCC#5]
/usr/bin/xcrun xcodebuild -workspace /private/var/www/xcz-ios/Carthage/Checkouts/SwiftyOpenCC/OpenCC.xcworkspace -scheme OpenCC\ macOS -configuration Release -derivedDataPath /Users/hustlzp/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/SwiftyOpenCC/v0.2.2 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/rr/xgdjh1jd35bdrqzf5xd6c8r00000gn/T/SwiftyOpenCC SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /var/www/xcz-ios/Carthage/Checkouts/SwiftyOpenCC)User defaults from command line:
    IDEArchivePathOverride = /var/folders/rr/xgdjh1jd35bdrqzf5xd6c8r00000gn/T/SwiftyOpenCC
    IDEDerivedDataPathOverride = /Users/hustlzp/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/SwiftyOpenCC/v0.2.2

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

--- xcodebuild: WARNING: Unable to open project file '/var/www/xcz-ios/Carthage/Checkouts/SwiftyOpenCC/OpenCC.playground' in workspace '/private/var/www/xcz-ios/Carthage/Checkouts/SwiftyOpenCC/OpenCC.xcworkspace'.
note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'OpenCC macOS')

** ARCHIVE FAILED **

**Comment by ddddxxx** [comment]
Please use master branch, which works fine for me.

**Comment by ddddxxx** [comment]
v1.0.0 is released, enjoy.

**Comment by hustlzp** [comment]
Thanks!
