### ISSUE TITLE
File STPhrases not found

### ISSUE THREAD

**Issue by hustlzp** [ddddxxx/SwiftyOpenCC#6]
Carthage version: 0.32.0
Xcode version: 10.2
Swift version: 5.0

Test codes:

```swift
let converter = try? ChineseConverter(option: [.traditionalize])
print(converter?.convert("诗词"))
```

Error:

<img width="950" alt="屏幕快照 2019-03-31 下午4 26 58" src="https://user-images.githubusercontent.com/1180240/55286711-02663100-53d2-11e9-9ddb-8d7074a50baf.png">

I install SwiftyOpenCC via `Carthage` instructions:

https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

Did I miss something?

**Comment by hustlzp** [comment]
Seems that the `Dictionary` directory does't exist in `OpenCC.framework`:

<img width="417" alt="屏幕快照 2019-03-31 下午4 35 45" src="https://user-images.githubusercontent.com/1180240/55286802-1cecda00-53d3-11e9-9db5-f5fa680f5815.png">

**Comment by ddddxxx** [comment]
Yes, The dictionary is not shipped with the framework. You need to pass it manually.

```swift
/// Returns an initialized `ChineseConverter` instance with the specified
/// conversion option.
///
/// - Parameter bundle: The bundle used to store the dictionary file. Pass
///   nil for the main bundle.
/// - Parameter option: The convert’s option.
public convenience init(bundle: Bundle? = nil, option: Options) throws
```

You can find the precompiled bundle [here](https://github.com/ddddxxx/SwiftyOpenCC/tree/master/OpenCCDictionary.bundle).

**Comment by hustlzp** [comment]
Solved, thanks!

**Comment by jerryeechan** [comment]
I Suggest that note this in README, thanks!

**Comment by ddddxxx** [comment]
@jerrypupu111 Done, thx
