### ISSUE TITLE
Unexpected CFBundleExcutable key

### ISSUE THREAD

**Issue by hustlzp** [ddddxxx/SwiftyOpenCC#7]
<img width="812" alt="屏幕快照 2019-04-04 上午12 48 35" src="https://user-images.githubusercontent.com/1180240/55498689-ce5f6a00-5676-11e9-810d-9f91d93b8e5b.png">

After delete the CFBundleExcutable key, I can upload my ipa successfully.

**Comment by ddddxxx** [comment]
Deleted, thanks!
